project:
  type: book
  output-dir: docs

book:
  title: "Statistics Notes"
  author: "andrés castro araújo"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - part: 00-regression.qmd
      chapters:
        - std-errors.qmd
        - marginal-effects.qmd
    - part: causality-00-intro.qmd
      chapters:
        - causality-01-experiments.qmd
        - causality-02-regression.qmd
        - causality-03-matching.qmd
        - causality-04-time.qmd
    - part: other-00-intro.qmd
      chapters:
        - other-01-gps.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lumen
    mainfont: Amiri
    monofont: Fira Code
    fontsize: 1em

fig-align: center

editor: visual

execute:
  echo: true
  freeze: auto

